/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container": "#171a1e",
        "on-secondary-container": "#fff5fb",
        "secondary-fixed": "#f6bfff",
        "on-primary": "#005d63",
        "tertiary-container": "#3956fb",
        "inverse-primary": "#006a71",
        "surface-container-low": "#111417",
        "on-background": "#f8f9fe",
        "on-tertiary-container": "#ffffff",
        "primary-fixed-dim": "#00deec",
        "surface-container-lowest": "#000000",
        "secondary-container": "#9d00c5",
        "surface-bright": "#282c32",
        "tertiary-dim": "#4963ff",
        "surface-container-high": "#1c2025",
        "error-container": "#9f0519",
        "tertiary-fixed-dim": "#8d9cff",
        "surface-variant": "#22262b",
        "surface-dim": "#0c0e12",
        "secondary-dim": "#c000f1",
        "tertiary-fixed": "#9eabff",
        "tertiary": "#8596ff",
        "on-surface-variant": "#a9abb0",
        "on-tertiary": "#001269",
        "on-surface": "#f8f9fe",
        "primary-container": "#00eefc",
        "error": "#ff716c",
        "surface-tint": "#8ff5ff",
        "on-primary-container": "#005359",
        "surface-container-highest": "#22262b",
        "background": "#0c0e12",
        "on-error-container": "#ffa8a3",
        "secondary": "#e06dff",
        "primary": "#8ff5ff",
        "on-secondary-fixed-variant": "#8800aa",
        "error-dim": "#d7383b",
        "on-error": "#490006",
        "on-tertiary-fixed-variant": "#0023ab",
        "outline": "#73757a",
        "secondary-fixed-dim": "#f1abff",
        "outline-variant": "#46484c",
        "on-secondary-fixed": "#5b0073",
        "on-tertiary-fixed": "#000c54",
        "surface": "#0c0e12",
        "on-primary-fixed": "#003f43",
        "inverse-surface": "#f8f9fe",
        "on-primary-fixed-variant": "#005e64",
        "on-secondary": "#3b004c",
        "primary-fixed": "#00eefc",
        "primary-dim": "#00deec",
        "inverse-on-surface": "#535559"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"]
      }
    },
  },
  plugins: [],
}
